### ISSUE TITLE
ypr parameter load from .csv fails

### ISSUE THREAD

**Issue by PAskey** [hctfbc/ypr#44]
When loading the ypr parameters from a .csv with the online ShinyApp, the upload seems to occur, but parameters do not change.
Running the app from R, and using the provided .csv template (with columns named "Parameter and"Value") I get the error message:
Error : Column names in uploaded data must be 'Parameter' and 'Value'.
Parsed with column specification:
cols(
  Parameter = col_character(),
  Value = col_double(),
  Description = col_character()
)

**Comment by sebdalgarno** [comment]
thanks for the bug report! it should be fixed now...both on the online app and from the R package.
Please test and let me know...

**Comment by PAskey** [comment]
Hi Seb,

Thanks for getting back so quick. Still having the same issues.

Here is a .csv. I just took your template and changed some values.

Online – It indicates “upload complete”, but there is no change from defaults.
From R I get the same error message as before.

Paul

**Comment by sebdalgarno** [comment]
hi @PAskey please try the online version now here https://poissonconsulting.shinyapps.io/ypr-shiny/

for testing the R package version please make sure you reinstall the package and restart your R session

**Comment by PAskey** [comment]
Thanks Seb,

Works now online and in R.

I installed the developmental versions of ypr and shinyypr. Is that the best option?

Paul

**Comment by sebdalgarno** [comment]
yes that is the best option - thanks!
